import { TurnoverFilters, TurnoverQueryBuilder } from '../interfaces/turnover-filters.interface';

// Dashboard Executivo - Visão consolidada com todos os KPIs principais
export const getDashboardExecutivoQuery = (filters: TurnoverFilters = {}): string => {
  const validation = TurnoverQueryBuilder.validateFilters(filters);
  if (!validation.valid) {
    throw new Error(validation.error);
  }

  const whereClause = TurnoverQueryBuilder.buildWhereClause(
    filters,
    { func: 'F', dept: 'D', cargo: 'C', emp: 'EMP' },
    {}
  );

  const { dataInicio, dataFim } = TurnoverQueryBuilder.getDateRange(filters);

  return `
WITH HEADCOUNT_ATUAL AS (
    SELECT COUNT(*) AS TOTAL
    FROM TFPFUN F
    LEFT JOIN TFPDEP D ON F.CODDEP = D.CODDEP
    LEFT JOIN TFPCAR C ON F.CODCARGO = C.CODCARGO
    LEFT JOIN TSIEMP EMP ON EMP.CODEMP = F.CODEMP
    WHERE F.SITUACAO = '1'
      ${whereClause}
),
HEADCOUNT_MES_ANTERIOR AS (
    SELECT COUNT(*) AS TOTAL
    FROM TFPFUN F
    LEFT JOIN TFPDEP D ON F.CODDEP = D.CODDEP
    LEFT JOIN TFPCAR C ON F.CODCARGO = C.CODCARGO
    LEFT JOIN TSIEMP EMP ON EMP.CODEMP = F.CODEMP
    WHERE (F.DTADM < DATEADD(MONTH, -1, GETDATE()) OR F.DTADM IS NULL)
      AND (F.SITUACAO = '1' OR (F.DTDEM >= DATEADD(MONTH, -1, GETDATE()) AND F.DTDEM < GETDATE()))
      ${whereClause}
),
ADMISSOES_MES AS (
    SELECT COUNT(*) AS TOTAL
    FROM TFPFUN F
    LEFT JOIN TFPDEP D ON F.CODDEP = D.CODDEP
    LEFT JOIN TFPCAR C ON F.CODCARGO = C.CODCARGO
    LEFT JOIN TSIEMP EMP ON EMP.CODEMP = F.CODEMP
    WHERE F.DTADM >= DATEADD(MONTH, -1, GETDATE())
      ${whereClause}
),
ADMISSOES_ANO AS (
    SELECT COUNT(*) AS TOTAL
    FROM TFPFUN F
    LEFT JOIN TFPDEP D ON F.CODDEP = D.CODDEP
    LEFT JOIN TFPCAR C ON F.CODCARGO = C.CODCARGO
    LEFT JOIN TSIEMP EMP ON EMP.CODEMP = F.CODEMP
    WHERE F.DTADM >= DATEADD(YEAR, -1, GETDATE())
      ${whereClause}
),
DEMISSOES_MES AS (
    SELECT COUNT(*) AS TOTAL
    FROM TFPFUN F
    LEFT JOIN TFPDEP D ON F.CODDEP = D.CODDEP
    LEFT JOIN TFPCAR C ON F.CODCARGO = C.CODCARGO
    LEFT JOIN TSIEMP EMP ON EMP.CODEMP = F.CODEMP
    WHERE F.DTDEM >= DATEADD(MONTH, -1, GETDATE())
      AND F.DTDEM < GETDATE()
      AND F.DTDEM IS NOT NULL
      ${whereClause}
),
DEMISSOES_ANO AS (
    SELECT COUNT(*) AS TOTAL
    FROM TFPFUN F
    LEFT JOIN TFPDEP D ON F.CODDEP = D.CODDEP
    LEFT JOIN TFPCAR C ON F.CODCARGO = C.CODCARGO
    LEFT JOIN TSIEMP EMP ON EMP.CODEMP = F.CODEMP
    WHERE F.DTDEM >= DATEADD(YEAR, -1, GETDATE())
      AND F.DTDEM IS NOT NULL
      ${whereClause}
),
CUSTO_ESTIMADO_MES AS (
    SELECT 
        SUM(F.SALBASE * 2.5) AS TOTAL
    FROM TFPFUN F
    LEFT JOIN TFPDEP D ON F.CODDEP = D.CODDEP
    LEFT JOIN TFPCAR C ON F.CODCARGO = C.CODCARGO
    LEFT JOIN TSIEMP EMP ON EMP.CODEMP = F.CODEMP
    WHERE F.DTDEM >= DATEADD(MONTH, -1, GETDATE())
      AND F.DTDEM < GETDATE()
      AND F.DTDEM IS NOT NULL
      ${whereClause}
),
CUSTO_ESTIMADO_ANO AS (
    SELECT 
        SUM(F.SALBASE * 2.5) AS TOTAL
    FROM TFPFUN F
    LEFT JOIN TFPDEP D ON F.CODDEP = D.CODDEP
    LEFT JOIN TFPCAR C ON F.CODCARGO = C.CODCARGO
    LEFT JOIN TSIEMP EMP ON EMP.CODEMP = F.CODEMP
    WHERE F.DTDEM >= DATEADD(YEAR, -1, GETDATE())
      AND F.DTDEM IS NOT NULL
      ${whereClause}
),
FUNCIONARIOS_RISCO AS (
    SELECT COUNT(*) AS TOTAL
    FROM TFPFUN F
    LEFT JOIN TFPDEP D ON F.CODDEP = D.CODDEP
    LEFT JOIN TFPCAR C ON F.CODCARGO = C.CODCARGO
    LEFT JOIN TSIEMP EMP ON EMP.CODEMP = F.CODEMP
    WHERE F.SITUACAO = '1'
      AND (
          DATEDIFF(MONTH, F.DTADM, GETDATE()) < 6 
          OR DATEDIFF(MONTH, F.DTADM, GETDATE()) > 36
          OR F.SALBASE < (
              SELECT AVG(F2.SALBASE) * 0.85 
              FROM TFPFUN F2 
              WHERE F2.CODCARGO = F.CODCARGO AND F2.SITUACAO = '1'
          )
      )
      ${whereClause}
),
DEPARTAMENTOS_CRITICOS AS (
    SELECT COUNT(DISTINCT CODDEP) AS TOTAL
    FROM (
        SELECT 
            F.CODDEP,
            COUNT(CASE WHEN F.DTDEM >= DATEADD(YEAR, -1, GETDATE()) THEN 1 END) * 100.0 / 
            COUNT(*) AS TAXA_TURNOVER
        FROM TFPFUN F
        LEFT JOIN TFPDEP D ON F.CODDEP = D.CODDEP
        LEFT JOIN TFPCAR C ON F.CODCARGO = C.CODCARGO
        LEFT JOIN TSIEMP EMP ON EMP.CODEMP = F.CODEMP
        WHERE F.SITUACAO IN ('0', '1')
          ${whereClause}
        GROUP BY F.CODDEP
        HAVING COUNT(CASE WHEN F.DTDEM >= DATEADD(YEAR, -1, GETDATE()) THEN 1 END) * 100.0 / COUNT(*) > 40
    ) D
)
SELECT 
    -- Headcount
    (SELECT TOTAL FROM HEADCOUNT_ATUAL) AS HEADCOUNT_ATUAL,
    (SELECT TOTAL FROM HEADCOUNT_ATUAL) - (SELECT TOTAL FROM HEADCOUNT_MES_ANTERIOR) AS HEADCOUNT_VARIACAO_MES,
    CAST(
        ((SELECT TOTAL FROM HEADCOUNT_ATUAL) - (SELECT TOTAL FROM HEADCOUNT_MES_ANTERIOR)) * 100.0 / 
        NULLIF((SELECT TOTAL FROM HEADCOUNT_MES_ANTERIOR), 0)
        AS DECIMAL(5,2)
    ) AS HEADCOUNT_VARIACAO_PERCENTUAL,
    
    -- Turnover
    CAST(
        (SELECT TOTAL FROM DEMISSOES_MES) * 100.0 / 
        NULLIF((SELECT TOTAL FROM HEADCOUNT_ATUAL), 0)
        AS DECIMAL(5,2)
    ) AS TURNOVER_TAXA_MES,
    CAST(
        (SELECT TOTAL FROM DEMISSOES_ANO) * 100.0 / 
        NULLIF((SELECT TOTAL FROM HEADCOUNT_ATUAL), 0)
        AS DECIMAL(5,2)
    ) AS TURNOVER_TAXA_ANO,
    15.0 AS TURNOVER_META,
    CASE 
        WHEN CAST(
            (SELECT TOTAL FROM DEMISSOES_ANO) * 100.0 / 
            NULLIF((SELECT TOTAL FROM HEADCOUNT_ATUAL), 0)
            AS DECIMAL(5,2)
        ) > 15.0 THEN 'ACIMA_META'
        ELSE 'DENTRO_META'
    END AS TURNOVER_STATUS,
    
    -- Custos
    CAST(COALESCE((SELECT TOTAL FROM CUSTO_ESTIMADO_MES), 0) AS DECIMAL(15,2)) AS CUSTO_MES_ATUAL,
    CAST(COALESCE((SELECT TOTAL FROM CUSTO_ESTIMADO_ANO), 0) AS DECIMAL(15,2)) AS CUSTO_ANO_ACUMULADO,
    CAST(COALESCE((SELECT TOTAL FROM CUSTO_ESTIMADO_ANO), 0) * 12.0 / DATEDIFF(MONTH, DATEADD(YEAR, -1, GETDATE()), GETDATE()) AS DECIMAL(15,2)) AS CUSTO_PROJECAO_ANO,
    
    -- Admissões
    (SELECT TOTAL FROM ADMISSOES_MES) AS ADMISSOES_MES,
    CAST((SELECT TOTAL FROM ADMISSOES_ANO) * 1.0 / 12 AS DECIMAL(10,1)) AS ADMISSOES_MEDIA_MENSAL,
    45 AS ADMISSOES_TEMPO_MEDIO_DIAS,
    
    -- Demissões
    (SELECT TOTAL FROM DEMISSOES_MES) AS DEMISSOES_MES,
    (SELECT COUNT(*) FROM TFPFUN F WHERE F.DTDEM >= DATEADD(MONTH, -1, GETDATE()) AND F.DTDEM < GETDATE()) AS DEMISSOES_VOLUNTARIAS,
    0 AS DEMISSOES_INVOLUNTARIAS,
    
    -- Riscos
    (SELECT TOTAL FROM FUNCIONARIOS_RISCO) AS FUNCIONARIOS_ALTO_RISCO,
    (SELECT TOTAL FROM DEPARTAMENTOS_CRITICOS) AS DEPARTAMENTOS_CRITICOS,
    
    -- Metadata
    GETDATE() AS DATA_ATUALIZACAO
`;
};
