export const getFuncionariosPorDepartamentoQuery = `
SELECT 
    D.DESCRDEP AS DEPARTAMENTO,
    S.DESCRSETOR AS SETOR,
    C.DESCRCARGO AS CARGO,
    COUNT(*) AS TOTAL_ATIVOS
FROM TFPFUN F
LEFT JOIN TFPDEP D ON F.CODDEP = D.CODDEP
LEFT JOIN TFPSET S ON F.CODSETOR = S.CODSETOR
LEFT JOIN TFPCAR C ON F.CODCARGO = C.CODCARGO
WHERE F.SITUACAO = '1'
GROUP BY 
    D.DESCRDEP, S.DESCRSETOR, C.DESCRCARGO
ORDER BY 
    D.DESCRDEP, S.DESCRSETOR, C.DESCRCARGO
`;

export const getTurnoverComFiltrosQuery = `
WITH BASE AS (
    SELECT 
        F.CODFUNC,
        F.DTADM,
        F.DTDEM,
        D.DESCRDEP AS DEPARTAMENTO,
        C.DESCRCARGO AS CARGO,
        S.DESCRSETOR AS SETOR
    FROM TFPFUN F
    LEFT JOIN TFPDEP D ON F.CODDEP = D.CODDEP
    LEFT JOIN TFPCAR C ON F.CODCARGO = C.CODCARGO
    LEFT JOIN TFPSET S ON F.CODSETOR = S.CODSETOR
),
AD AS (
    SELECT 
        FORMAT(DTADM, 'yyyy-MM') AS ANO_MES,
        DEPARTAMENTO,
        SETOR,
        CARGO,
        COUNT(*) AS ADM
    FROM BASE
    WHERE DTADM BETWEEN @dataInicio AND @dataFim
    GROUP BY FORMAT(DTADM, 'yyyy-MM'), DEPARTAMENTO, SETOR, CARGO
),
DE AS (
    SELECT 
        FORMAT(DTDEM, 'yyyy-MM') AS ANO_MES,
        DEPARTAMENTO,
        SETOR,
        CARGO,
        COUNT(*) AS DEM
    FROM BASE
    WHERE DTDEM IS NOT NULL
      AND DTDEM BETWEEN @dataInicio AND @dataFim
    GROUP BY FORMAT(DTDEM, 'yyyy-MM'), DEPARTAMENTO, SETOR, CARGO
),
TOTAL AS (
    SELECT 
        DEPARTAMENTO, SETOR, CARGO,
        COUNT(*) AS TOTAL_ATUAIS
    FROM BASE
    WHERE DTDEM IS NULL
    GROUP BY DEPARTAMENTO, SETOR, CARGO
)
SELECT
    COALESCE(A.ANO_MES, D.ANO_MES) AS ANO_MES,
    COALESCE(A.DEPARTAMENTO, D.DEPARTAMENTO) AS DEPARTAMENTO,
    COALESCE(A.SETOR, D.SETOR) AS SETOR,
    COALESCE(A.CARGO, D.CARGO) AS CARGO,
    COALESCE(A.ADM, 0) AS ADMISSOES,
    COALESCE(D.DEM, 0) AS DEMISSOES,
    CASE 
        WHEN T.TOTAL_ATUAIS > 0 
        THEN CAST(COALESCE(D.DEM, 0) * 100.0 / T.TOTAL_ATUAIS AS DECIMAL(10,2))
        ELSE 0 
    END AS TURNOVER
FROM AD A
FULL JOIN DE D ON A.ANO_MES = D.ANO_MES 
   AND A.DEPARTAMENTO = D.DEPARTAMENTO
   AND A.SETOR = D.SETOR
   AND A.CARGO = D.CARGO
LEFT JOIN TOTAL T ON T.DEPARTAMENTO = COALESCE(A.DEPARTAMENTO, D.DEPARTAMENTO)
                   AND T.SETOR = COALESCE(A.SETOR, D.SETOR)
                   AND T.CARGO = COALESCE(A.CARGO, D.CARGO)
ORDER BY ANO_MES DESC, DEPARTAMENTO, SETOR, CARGO
`;

export const getTempoEmpresaQuery = `
SELECT 
    CASE 
        WHEN DATEDIFF(YEAR, DTADM, GETDATE()) < 1 THEN '0-1 ano'
        WHEN DATEDIFF(YEAR, DTADM, GETDATE()) BETWEEN 1 AND 3 THEN '1-3 anos'
        WHEN DATEDIFF(YEAR, DTADM, GETDATE()) BETWEEN 3 AND 5 THEN '3-5 anos'
        ELSE '5+ anos'
    END AS FAIXA_TEMPO_CASA,
    COUNT(*) AS TOTAL
FROM TFPFUN
WHERE SITUACAO = '1'
GROUP BY 
    CASE 
        WHEN DATEDIFF(YEAR, DTADM, GETDATE()) < 1 THEN '0-1 ano'
        WHEN DATEDIFF(YEAR, DTADM, GETDATE()) BETWEEN 1 AND 3 THEN '1-3 anos'
        WHEN DATEDIFF(YEAR, DTADM, GETDATE()) BETWEEN 3 AND 5 THEN '3-5 anos'
        ELSE '5+ anos'
    END
ORDER BY TOTAL DESC
`;

export const getFaixaEtariaQuery = `
SELECT 
    CASE
        WHEN DATEDIFF(YEAR, DTNASC, GETDATE()) < 20 THEN 'Menos de 20'
        WHEN DATEDIFF(YEAR, DTNASC, GETDATE()) BETWEEN 20 AND 29 THEN '20-29'
        WHEN DATEDIFF(YEAR, DTNASC, GETDATE()) BETWEEN 30 AND 39 THEN '30-39'
        WHEN DATEDIFF(YEAR, DTNASC, GETDATE()) BETWEEN 40 AND 49 THEN '40-49'
        ELSE '50+'
    END AS FAIXA_ETARIA,
    COUNT(*) AS TOTAL
FROM TFPFUN
WHERE SITUACAO = '1'
GROUP BY
    CASE
        WHEN DATEDIFF(YEAR, DTNASC, GETDATE()) < 20 THEN 'Menos de 20'
        WHEN DATEDIFF(YEAR, DTNASC, GETDATE()) BETWEEN 20 AND 29 THEN '20-29'
        WHEN DATEDIFF(YEAR, DTNASC, GETDATE()) BETWEEN 30 AND 39 THEN '30-39'
        WHEN DATEDIFF(YEAR, DTNASC, GETDATE()) BETWEEN 40 AND 49 THEN '40-49'
        ELSE '50+'
    END
ORDER BY TOTAL DESC
`;

export const getResumoTurnoverDepartamentoQuery = `
WITH ULTIMOS_DADOS AS (
    SELECT 
        D.DESCRDEP AS DEPARTAMENTO,
        COUNT(*) AS TOTAL_FUNCIONARIOS,
        SUM(CASE WHEN F.DTADM >= DATEADD(MONTH, -1, GETDATE()) THEN 1 ELSE 0 END) AS ADMISSOES_MES,
        SUM(CASE WHEN F.DTDEM >= DATEADD(MONTH, -1, GETDATE()) AND F.DTDEM IS NOT NULL THEN 1 ELSE 0 END) AS DEMISSOES_MES
    FROM TFPFUN F
    LEFT JOIN TFPDEP D ON F.CODDEP = D.CODDEP
    WHERE F.SITUACAO IN ('0', '1')
    GROUP BY D.DESCRDEP
)
SELECT 
    DEPARTAMENTO,
    TOTAL_FUNCIONARIOS,
    ADMISSOES_MES,
    DEMISSOES_MES,
    CASE 
        WHEN TOTAL_FUNCIONARIOS > 0 
        THEN CAST(DEMISSOES_MES * 100.0 / TOTAL_FUNCIONARIOS AS DECIMAL(10,2))
        ELSE 0 
    END AS TURNOVER_PERCENTUAL
FROM ULTIMOS_DADOS
ORDER BY TURNOVER_PERCENTUAL DESC
`;

export const getResumoTurnoverPeriodoQuery = `
WITH AD_PERIODO AS (
    SELECT 
        FORMAT(DTADM, 'yyyy-MM') AS ANO_MES,
        COUNT(*) AS TOTAL_ADMISSOES
    FROM TFPFUN
    WHERE DTADM BETWEEN @dataInicio AND @dataFim
    GROUP BY FORMAT(DTADM, 'yyyy-MM')
),
DEM_PERIODO AS (
    SELECT 
        FORMAT(DTDEM, 'yyyy-MM') AS ANO_MES,
        COUNT(*) AS TOTAL_DEMISSOES
    FROM TFPFUN
    WHERE DTDEM IS NOT NULL
      AND DTDEM BETWEEN @dataInicio AND @dataFim
    GROUP BY FORMAT(DTDEM, 'yyyy-MM')
),
TOTAL_FUNCIONARIOS AS (
    SELECT 
        COUNT(*) AS TOTAL
    FROM TFPFUN
    WHERE SITUACAO = '1'
)
SELECT
    COALESCE(A.ANO_MES, D.ANO_MES) AS ANO_MES,
    COALESCE(A.TOTAL_ADMISSOES, 0) AS TOTAL_ADMISSOES,
    COALESCE(D.TOTAL_DEMISSOES, 0) AS TOTAL_DEMISSOES,
    CASE 
        WHEN T.TOTAL > 0 
        THEN CAST(COALESCE(D.TOTAL_DEMISSOES, 0) * 100.0 / T.TOTAL AS DECIMAL(10,2))
        ELSE 0 
    END AS TURNOVER_MEDIO
FROM AD_PERIODO A
FULL JOIN DEM_PERIODO D ON A.ANO_MES = D.ANO_MES
CROSS JOIN TOTAL_FUNCIONARIOS T
ORDER BY ANO_MES DESC
`;

export const getAnaliseDesligamentosQuery = `
SELECT 
    F.CODFUNC,
    F.NOME,
    D.DESCRDEP AS DEPARTAMENTO,
    C.DESCRCARGO AS CARGO,
    F.DTADM,
    F.DTDEM,
    DATEDIFF(DAY, F.DTADM, F.DTDEM) AS TEMPO_EMPRESA_DIAS
FROM TFPFUN F
LEFT JOIN TFPDEP D ON F.CODDEP = D.CODDEP
LEFT JOIN TFPCAR C ON F.CODCARGO = C.CODCARGO
WHERE F.DTDEM IS NOT NULL
  AND F.DTDEM BETWEEN @dataInicio AND @dataFim
ORDER BY F.DTDEM DESC
`;

export const getEstatisticasGeraisQuery = `
SELECT 
    (SELECT COUNT(*) FROM TFPFUN WHERE SITUACAO = '1') AS TOTAL_FUNCIONARIOS_ATIVOS,
    (SELECT COUNT(*) FROM TFPFUN WHERE DTDEM IS NOT NULL AND DTDEM >= DATEADD(MONTH, -12, GETDATE())) AS TOTAL_DESLIGADOS_PERIODO,
    (SELECT COUNT(*) FROM TFPFUN WHERE DTADM >= DATEADD(MONTH, -12, GETDATE())) AS ADMISSOES_PERIODO,
    CASE 
        WHEN (SELECT COUNT(*) FROM TFPFUN WHERE SITUACAO = '1') > 0
        THEN CAST(
            (SELECT COUNT(*) FROM TFPFUN WHERE DTDEM IS NOT NULL AND DTDEM >= DATEADD(MONTH, -12, GETDATE())) * 100.0 / 
            (SELECT COUNT(*) FROM TFPFUN WHERE SITUACAO = '1')
            AS DECIMAL(10,2)
        )
        ELSE 0
    END AS TURNOVER_MEDIO_PERCENTUAL
`;
