export const BASE_FROM = `\nFROM TFPFUN f\nJOIN TSIUSU u ON f.CODEMP = u.CODEMP AND f.CODFUNC = u.CODFUNC\nJOIN TFPDEP d ON d.CODDEP = f.CODDEP\nJOIN TFPCAR cg ON cg.CODCARGO = f.CODCARGO\nJOIN TSICUS cr ON cr.CODCENCUS = u.CODCENCUSPAD\nJOIN TSIEMP e ON e.CODEMP = f.CODEMP\nLEFT JOIN TFPCGH ch ON ch.CODCARGAHOR = f.CODCARGAHOR\nJOIN TGFPAR par ON par.CODPARC = f.CODPARC\n`;

export const PESSOAS_SELECT = `
	SELECT
		f.CODFUNC,
		f.CODEMP,
		f.NOMEFUNC,
		FORMAT(CAST(f.DTNASC AS DATE), 'dd/MM/yyyy') AS DTNASC,
		DATEDIFF(YEAR, CAST(f.DTNASC AS DATE), GETDATE())
			- CASE
					WHEN MONTH(CAST(f.DTNASC AS DATE)) > MONTH(GETDATE())
						OR (MONTH(CAST(f.DTNASC AS DATE)) = MONTH(GETDATE())
						AND DAY(CAST(f.DTNASC AS DATE)) > DAY(GETDATE()))
					THEN 1 ELSE 0
				END AS IDADE,
		FORMAT(f.DTADM, 'dd/MM/yyyy') AS DTADM,
		DATEDIFF(DAY, f.DTADM, GETDATE()) AS DIAS_ADMISSAO,
		SUBSTRING(f.CPF,1,3) + '.' + SUBSTRING(f.CPF,4,3) + '.' + SUBSTRING(f.CPF,7,3) + '-' + SUBSTRING(f.CPF,10,2) AS CPF,
		f.CELULAR,
		f.EMAIL,
		f.SITUACAO,
		u.CODUSU,
		u.NOMEUSU,
		u.EMAIL AS EMAIL_USUARIO,
		u.AD_TELEFONECORP,
		ch.DESCRCARGAHOR,
		d.DESCRDEP,
		COALESCE(cg.DESCRCARGO, 'Nao informado') AS DESCRCARGO,
		cr.DESCRCENCUS,
		e.CODEMP AS EMPRESA_CODEMP,
		e.NOMEFANTASIA,
		SUBSTRING(e.CGC, 1, 2) + '.' + SUBSTRING(e.CGC, 3, 3) + '.' + SUBSTRING(e.CGC, 6, 3) + '/' + SUBSTRING(e.CGC, 9, 4) + '-' + SUBSTRING(e.CGC, 13, 2) AS CNPJ
`;
