export const BASE_FROM = `\nFROM TFPFUN f\nJOIN TSIUSU u ON f.CODEMP = u.CODEMP AND f.CODFUNC = u.CODFUNC\nJOIN TFPDEP d ON d.CODDEP = f.CODDEP\nJOIN TFPCAR cg ON cg.CODCARGO = f.CODCARGO\nJOIN TSICUS cr ON cr.CODCENCUS = u.CODCENCUSPAD\nJOIN TSIEMP e ON e.CODEMP = f.CODEMP\nLEFT JOIN TFPCGH ch ON ch.CODCARGAHOR = f.CODCARGAHOR\n`;

export const PESSOAS_SELECT = `\n  SELECT\n    f.CODFUNC,\n    f.NOMEFUNC,\n    FORMAT(f.DTADM, 'dd/MM/yyyy') AS DTADM,\n    f.EMAIL,\n    f.CELULAR,\n    f.SITUACAO,\n    d.DESCRDEP,\n    cg.DESCRCARGO,\n    e.NOMEFANTASIA\n`;
