-- Consulta exemplo JOIN entre TFPFUN, TSIUSU e TGFPAR
SELECT TOP 10
  F.CODEMP,
  F.CODFUNC,
  F.NOMEFUNC,
  U.CODUSU,
  U.NOMEUSU,
  P.CODPARC,
  P.NOMEPARC
FROM TFPFUN F
LEFT JOIN TSIUSU U
  ON F.CODEMP = U.CODEMP AND F.CODFUNC = U.CODFUNC
LEFT JOIN TGFPAR P
  ON F.CODPARC = P.CODPARC
ORDER BY F.DTADM DESC;
